import "./globals.css";
import type { Metadata } from "next";
import "react-toastify/dist/ReactToastify.css";
import { Geist, Geist_Mono } from "next/font/google";

import { User } from "@/utils/interfaces/User";
import { Todo } from "@/utils/interfaces/Todo";
import { getUser } from "@/app/actions/auth/user";
import { getTodos } from "@/app/actions/todo/todo";
import Header from "@/components/dashboard/Header";
import StateHydrator from "@/components/StateHydrator";
import JotaiProvider from "@/utils/providers/JotaiProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userData = await getUser();
  const { todos: todoList } = await getTodos();
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
      >
        <JotaiProvider>
          <Header />
          {children}
           <StateHydrator user={ userData as User } todos={ todoList as Todo[] } />
        </JotaiProvider>
      </body>
    </html>
  );
}
